---
title: "List Howto"
author: "Paul roetman"
date: "27 May 2017"
output: 
  html_document:
    toc: TRUE
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# List Howto

## Create List

Lists can contain different types.

```{r}
my_list <- list(a=1, b=2)
my_list
```

### Rename elements
```{r}
element_names <- c('e1','e2')
names(my_list) <- element_names
my_list
```

### Different Types
```{r}
x <- list(1, "a", T, 1+4i)
x
```

### Reference Lists

Return as a list
```{r}
x <- list(foo = 1:4, bar = 0.6, fff = 'c')
x
b = x[1]    # just first element as a new list
class(b)
b
x["bar"]    
```

Return as a vector
```{r}
b = x[[1]]  # returns a vector
class(b)
b
x$bar       # also returns a vector
x$b         # partial match
x$f         # fails as there are two starting with "f" 

```

Use double brackets to reference list by var
```{r}
name <- "foo"
x[[name]]
x$name           # fails
```

### Lists of lists

```{r}
x <- list(a=list(10,12,14), b=c(1,2))
x

x[[c(1,3)]]   # 3rd element of 1st list
x[[1]][[3]]   # 3rd element of 1st list

```

### generic List example

```{r}
myList <- list(letters=c('A','b','c'), numbers=1:3, matrix(1:25, ncol=5))
head(myList)
# Reference first var
myList[1]
myList$letters
myList[[1]]
```
