---
title: "Week4 Peer Graded"
author: "Paul Roetman"
date: "14 June 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Week 4 Peer Graded Assignment

Notes:

1) a tidy data set as described below
2) a link to a Github repository with your script for performing the analysis
3) a code book that describes the variables, the data, and any transformations or work that you performed to clean up the data called CodeBook.md
4) include a README.md in the repo with your scripts. This repo explains how all of the scripts work and how they are connected.

ToDo:
 create one R script called run_analysis.R that does the following.

* Merges the training and the test sets to create one data set.
* Extracts only the measurements on the mean and standard deviation for each measurement.
* Uses descriptive activity names to name the activities in the data set
* Appropriately labels the data set with descriptive variable names.
* From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.


* Merge train and test
* get mean and standard deviation for each measurement
